services:
  - type: web
    name: steam-dead-ranker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DISCORD_WEBHOOK_URL
        sync: false
      - key: LINKS_FILE
        value: steam_links.txt
      - key: TOP_N
        value: "30"
      - key: MAX_PER_RUN
        value: "9999"
      - key: BATCH_DELAY_S
        value: "1.5"
